# Start: Manejo de excepciones
## Sintaxis b√°sica
# try:
#     # Introduce el c√≥digo que puede fallar.
#     pass
# except TipoError1:
#     # Se ejecuta si ocurre TipoError1.
#     pass
# except (TipoError2, TipoError3):
#     # Se ejecuta si ocurre TipoError2 o el TipoError3.
#     pass
# else:
#     # Se ejecuta si no hubo ninguna excepci√≥n.
#     pass
# finally:
#     # Se ejecuta siempre al final (limpieza).
#     pass

## Ejemplo con ValueError
# Sin manejo de excepciones:
# while True:
#     numero = int(input("Ingresa un n√∫mero entero: "))
#     print(f"N√∫mero ingresado: {numero}")
#     print("Intento de entrada finalizado.\n")
#     break

# Con manejo de excepciones:
# while True:
#     try:
#         numero = int(input("Ingresa un n√∫mero entero: "))
#         print(f"N√∫mero ingresado: {numero}")
#         break
#     except ValueError:
#         print("Error: Debes ingresar un n√∫mero entero. Intenta nuevamente.")
#     finally:
#         print("Intento de entrada finalizado.\n")

## Ejemplo con ValueError y ZeroDivisionError
# Sin manejo de excepciones:
# def division(a, b):
#     return a/b

# while True:
#     numero_1 = int(input("Ingresa un n√∫mero entero: "))
#     numero_2 = int(input("Ingresa otro n√∫mero entero: "))
#     resultado = division(a=numero_1, b=numero_2)
#     print(f"El resultado es: {resultado}")
#     print("Intento de entrada finalizado.\n")
#     break


# Con manejo de excepciones:
# def division(a, b):
#     return a/b

# while True:
#     try:
#         numero_1 = int(input("Ingresa un n√∫mero entero: "))
#         numero_2 = int(input("Ingresa otro n√∫mero entero: "))
#         resultado = division(a=numero_1, b=numero_2)
#         print(f"El resultado es: {resultado}")
#         break
#     except ValueError:
#         print("Error: Debes ingresar un n√∫mero entero. Intenta nuevamente.")
#     except ZeroDivisionError:
#         print("Error: No puedes dividir entre cero.")
#     finally:
#         print("Intento de entrada finalizado.\n")

## Manejo de m√∫ltiples excepciones (captura del mensaje del error)
# try:
#     numero = int(input("Introduce un n√∫mero: "))
#     resultado = 10 / numero
# except (ValueError, ZeroDivisionError) as error_var:
#     print(f"Error: {error_var}")

## Exception
# Ejemplo 1:
# try:
#     x = int("hola")  # Esto generar√° un ValueError
# except Exception as e:
#     print(f"Se produjo un error: {e}")

# Ejemplo 2:
# try:
#     resultado = 5/0  # Esto generar√° un ZeroDivisionError
# except Exception as e:
#     print(f"Se produjo un error: {e}")

# End: Manejo de excepciones

# Start: Lanzando excepciones
# Sintaxis b√°sica: raise TipoDeError("Mensaje opcional")
# Sin manejo de excepciones:
# def verificar_edad(edad):
#     if edad < 0:
#         raise ValueError("La edad no puede ser negativa.")
#     print(f"Edad v√°lida: {edad}")

# verificar_edad(-5) # Esto generar√° un ValueError


# Con manejo de excepciones:
# def verificar_edad(edad):
#     if edad < 0:
#         raise ValueError("La edad no puede ser negativa.")
#     print(f"Edad v√°lida: {edad}")

# try:
#     verificar_edad(-5) # Esto generar√° un ValueError
# except ValueError as e:
#     print(f'Error: {e}')

## Bonus: Uso de any()
# texto = "python es Genial"
# print(any(char.isupper() for char in texto))

# End: Lanzando excepciones

# Start: Decoradores
# def requiere_permiso(func):
#     """Funci√≥n para preguntar si un usuario tiene permiso."""

#     def wrapper(usuario, *args, **kwargs):
#         if usuario != "admin":
#             print("‚úñÔ∏è  Acceso denegado: no tienes permisos.")
#             return None
#         return func(usuario, *args, **kwargs)

#     return wrapper


# @requiere_permiso
# def eliminar_datos(usuario):
#     """Funci√≥n para simular la eliminaci√≥n de datos."""
#     print(f"üóëÔ∏è  Datos eliminados por {usuario}")


# eliminar_datos(usuario="invitado")
# eliminar_datos(usuario="admin")
# End: Decoradores
